---
pgcluster:
  vars:
    postgresql_pg_hba_custom:
      - { type: "host", database: "testdb", user: "all", method: "md5" }
      # NOTE: Add Database/User  1/5
      - { type: "host", database: "exampledb", user: "all", method: "md5" }

    # Databases
    postgresql_databases:
      - name: "{{ repmgr_database }}"
        owner: "{{ repmgr_user }}"
        encoding: "UTF-8"
      - name: testdb
        owner: admin
        encoding: "UTF-8"
      # NOTE: Add Database/User  2/5
      - name: exampledb
        owner: exampleuser
        encoding: "UTF-8"
    # Users
    postgresql_users:
      - name: "{{ repmgr_user }}"
        pass: "{{ repmgr_password }}"
      - name: admin
        pass: secret # postgresql >=10 does not accept unencrypted passwords
        encrypted: yes
      # NOTE: Add Database/User  3/5
      - name: exampleuser
        pass: secret # postgresql >=10 does not accept unencrypted passwords
        encrypted: yes
    # Roles
    postgresql_user_privileges:
      - name: admin
        db: testdb
        role_attr_flags: "SUPERUSER"
      # NOTE: Add Database/User  4/5
      - name: exampleuser
        db: exampledb
        role_attr_flags: "SUPERUSER"
    # prgbouncer
    pgbouncer_pools:
      - name: "testdb"
        dbname: "testdb"
        host: "localhost"
        port: "5432"
      # NOTE: Add Database/User  5/5
      - name: "exampledb"
        dbname: "exampledb"
        host: "localhost"
        port: "5432"
